version: '3.8'

services:
  # PostgreSQL 17 + pgvector
  postgres:
    image: pgvector/pgvector:pg17
    container_name: enterprise-kb-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=enterprise_kb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 企业知识库应用
  enterprise-kb-app:
    build: .
    container_name: enterprise-kb-app
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=jdbc:postgresql://postgres:5432/enterprise_kb
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - JPA_DDL_AUTO=update
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: